### ISSUE TITLE
Error in app.py

### ISSUE THREAD

**Issue by Maheshvinayvarma** [Maheshvinayvarma/WebApp#3]
@Maheshvinayvarma ➜ /workspaces/WebApp (main) $ /home/codespace/.python/current/bin/python3 /workspaces/WebApp/WebApp/D3js_Flask/app.py
Traceback (most recent call last):
  File "/workspaces/WebApp/WebApp/D3js_Flask/app.py", line 1, in <module>
    from flask import Flask, request,Response, render_template
ModuleNotFoundError: No module named 'flask'
@Maheshvinayvarma ➜ /workspaces/WebApp (main) $ /workspaces/WebApp/.venv/bin/python /workspaces/WebApp/WebApp/D3js_Flask/app.py
Traceback (most recent call last):
  File "/workspaces/WebApp/WebApp/D3js_Flask/app.py", line 14, in <module>
    def main():
  File "/workspaces/WebApp/.venv/lib/python3.10/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/workspaces/WebApp/.venv/lib/python3.10/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
  File "/workspaces/WebApp/.venv/lib/python3.10/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: main

**Comment by Maheshvinayvarma** [comment]
Issue resolved
